services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq  # Ensure RabbitMQ starts before the Django app
      - redis
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//  # Celery uses RabbitMQ as a broker
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Use Redis for task results

  rabbitmq:
    image: rabbitmq:3-management  # RabbitMQ with web management UI
    restart: always
    ports:
      - 5672:5672  # RabbitMQ messaging port
      - 15672:15672  # RabbitMQ management UI (http://localhost:15672)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: .
    command: celery -A ProjectCore worker --loglevel=info
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
