# Generated by Django 5.0.6 on 2025-02-07 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='sharedtruckes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Occupied', 'Occupied')], default='Free', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('full', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=50)),
                ('percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Occupied', 'Occupied')], default='Free', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('volume', models.FloatField()),
                ('maxweight', models.FloatField()),
                ('type', models.CharField(choices=[('Truck', 'Truck'), ('Van', 'Van'), ('Car', 'Car')], max_length=50)),
                ('full', models.BooleanField(default=False)),
                ('percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('liquid', 'Liquid'), ('fragile', 'Fragile'), ('Box', 'Box')], max_length=50)),
                ('volume', models.FloatField()),
                ('weight', models.FloatField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('begin', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('produit', models.ManyToManyField(to='Auth.produit', verbose_name='produits')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.FloatField()),
                ('price_per_day', models.FloatField()),
                ('shared_trucks', models.ManyToManyField(to='Auth.sharedtruckes', verbose_name='Shared Trucks')),
                ('trucks', models.ManyToManyField(to='Auth.truck', verbose_name='Trucks')),
            ],
        ),
        migrations.CreateModel(
            name='road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('begin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('delivery_time', models.FloatField()),
                ('success', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Auth.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('license', models.ImageField(blank=True, null=True, upload_to='images')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.transport', verbose_name='transports')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('company', 'Company'), ('transport', 'Transport'), ('admin', 'Admin')], max_length=50)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='Auth.company', verbose_name='Company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('transport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='Auth.transport', verbose_name='Transport')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
