# Generated by Django 5.0.6 on 2025-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='volume',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='volume',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='sharedtruckes',
            name='volume',
        ),
        migrations.AddField(
            model_name='produit',
            name='width',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedtruckes',
            name='height',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedtruckes',
            name='width',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='width',
            field=models.FloatField(default=233),
            preserve_default=False,
        ),
    ]
