# Generated by Django 5.0.6 on 2025-02-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_rename_volume_produit_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='price_per_day',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price_per_km',
            field=models.FloatField(null=True),
        ),
    ]
