# Generated by Django 5.0.6 on 2025-02-07 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_track_truck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='maxweight',
            new_name='weight',
        ),
    ]
