# Generated by Django 5.0.6 on 2025-02-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_rename_maxweight_truck_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='track',
            name='produit',
        ),
    ]
