# Generated by Django 5.0.6 on 2025-02-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_remove_track_amount_remove_track_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
