# Generated by Django 5.0.6 on 2025-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_track_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='trucks',
            field=models.ManyToManyField(null=True, to='Auth.truck', verbose_name='Trucks'),
        ),
    ]
